apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - server-deployment.yaml
  - server-service.yaml
images:
  - name: ghcr.io/robbertvdzon/agent-runtime-server
    newName: ghcr.io/robbertvdzon/agent-runtime-server
    newTag: sha-f4ae29910b24641e216a3ed9e7b8ea8182ae298e
