apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - server-deployment.yaml
  - server-service.yaml
images:
  - name: ghcr.io/robbertvdzon/agent-runtime-server
    newName: ghcr.io/robbertvdzon/agent-runtime-server
    newTag: sha-547eefe193fb39bec29ec1003912e3ac91994f4d
