apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - server-deployment.yaml
  - server-service.yaml
images:
  - name: ghcr.io/robbertvdzon/agent-runtime-server
    newName: ghcr.io/robbertvdzon/agent-runtime-server
    newTag: sha-3326c093b9079a4a213d7ed94b1594d0f5523515
