apiVersion: route.openshift.io/v1
kind: Route
metadata: {name: agent-runtime}
spec:
  host: agent-runtime.vdzonsoftware.nl
  to: {kind: Service, name: agent-runtime-server}
  port: {targetPort: http}
  tls: {termination: edge, insecureEdgeTerminationPolicy: Allow}
