CREATE TABLE runtime_job (
    id VARCHAR(36) PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    job_kind VARCHAR(40) NOT NULL,
    job_profile VARCHAR(100) NOT NULL,
    job_key VARCHAR(160) NOT NULL,
    provider VARCHAR(40) NOT NULL,
    model VARCHAR(100) NOT NULL,
    request_json TEXT NOT NULL,
    response_schema_json TEXT,
    status VARCHAR(40) NOT NULL,
    phase VARCHAR(80) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL,
    priority INTEGER NOT NULL,
    progress_percent INTEGER,
    progress_message VARCHAR(1000),
    result_json TEXT,
    usage_json TEXT,
    error_code VARCHAR(120),
    error_message VARCHAR(2000),
    cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
    not_before TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT runtime_job_idempotency UNIQUE (tenant_id, idempotency_key)
);

CREATE INDEX runtime_job_queue_idx ON runtime_job(status, not_before, priority, created_at);
CREATE INDEX runtime_job_tenant_idx ON runtime_job(tenant_id, created_at);

CREATE TABLE runtime_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id VARCHAR(36) NOT NULL REFERENCES runtime_job(id),
    event_type VARCHAR(100) NOT NULL,
    phase VARCHAR(80) NOT NULL,
    message VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE runtime_attempt (
    id VARCHAR(36) PRIMARY KEY,
    job_id VARCHAR(36) NOT NULL REFERENCES runtime_job(id),
    worker_id VARCHAR(100) NOT NULL,
    worker_boot_id VARCHAR(100) NOT NULL,
    attempt_number INTEGER NOT NULL,
    fencing_token_hash VARCHAR(64) NOT NULL,
    status VARCHAR(40) NOT NULL,
    lease_until TIMESTAMP WITH TIME ZONE NOT NULL,
    recovery_until TIMESTAMP WITH TIME ZONE,
    heartbeat_at TIMESTAMP WITH TIME ZONE NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX runtime_attempt_job_idx ON runtime_attempt(job_id, status);
CREATE INDEX runtime_attempt_lease_idx ON runtime_attempt(status, lease_until);

CREATE TABLE runtime_worker (
    worker_id VARCHAR(100) PRIMARY KEY,
    boot_id VARCHAR(100) NOT NULL,
    status VARCHAR(40) NOT NULL,
    capabilities_json TEXT NOT NULL,
    providers_json TEXT NOT NULL,
    models_json TEXT NOT NULL,
    versions_json TEXT NOT NULL,
    last_heartbeat_at TIMESTAMP WITH TIME ZONE NOT NULL,
    registered_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE runtime_artifact (
    id VARCHAR(36) PRIMARY KEY,
    job_id VARCHAR(36) NOT NULL REFERENCES runtime_job(id),
    filename VARCHAR(255) NOT NULL,
    mime_type VARCHAR(160) NOT NULL,
    size_bytes BIGINT NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    content BYTEA NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE runtime_mock_response (
    id VARCHAR(36) PRIMARY KEY,
    tenant_id VARCHAR(100),
    job_profile VARCHAR(100),
    job_key VARCHAR(160),
    consumer_correlation VARCHAR(200),
    result_json TEXT,
    error_code VARCHAR(120),
    error_message VARCHAR(2000),
    delay_millis BIGINT NOT NULL DEFAULT 0,
    consumed_by_job_id VARCHAR(36),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE runtime_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor VARCHAR(160) NOT NULL,
    action VARCHAR(160) NOT NULL,
    target_id VARCHAR(160),
    detail VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
