ALTER TABLE runtime_attempt ADD COLUMN attempt_deadline TIMESTAMP WITH TIME ZONE;
UPDATE runtime_attempt SET attempt_deadline = lease_until WHERE attempt_deadline IS NULL;
ALTER TABLE runtime_attempt ALTER COLUMN attempt_deadline SET NOT NULL;

ALTER TABLE runtime_worker ADD COLUMN environment_keys_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE runtime_worker ADD COLUMN max_concurrency INTEGER NOT NULL DEFAULT 1;
ALTER TABLE runtime_job ADD COLUMN cancelled_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE runtime_job ADD COLUMN cancelled_by VARCHAR(160);

CREATE TABLE runtime_input_attachment (
    id VARCHAR(36) PRIMARY KEY,
    job_id VARCHAR(36) NOT NULL REFERENCES runtime_job(id),
    filename VARCHAR(255) NOT NULL,
    mime_type VARCHAR(160) NOT NULL,
    size_bytes BIGINT NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    content BYTEA NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT runtime_input_attachment_name UNIQUE (job_id, filename)
);

CREATE TABLE runtime_output_attempt (
    id VARCHAR(36) PRIMARY KEY,
    job_id VARCHAR(36) NOT NULL REFERENCES runtime_job(id),
    execution_attempt_id VARCHAR(36) REFERENCES runtime_attempt(id),
    output_attempt_number INTEGER NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    status VARCHAR(40) NOT NULL,
    candidate_sha256 VARCHAR(64),
    diagnostic_excerpt VARCHAR(2000),
    validation_errors_json TEXT,
    accepted_result_json TEXT,
    usage_json TEXT,
    provider VARCHAR(40) NOT NULL,
    model VARCHAR(100) NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT runtime_output_attempt_number UNIQUE (job_id, output_attempt_number),
    CONSTRAINT runtime_output_attempt_idempotency UNIQUE (job_id, idempotency_key)
);

CREATE TABLE runtime_transcript (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id VARCHAR(36) NOT NULL REFERENCES runtime_job(id),
    attempt_id VARCHAR(36) NOT NULL REFERENCES runtime_attempt(id),
    part_id VARCHAR(100) NOT NULL,
    sequence_number BIGINT NOT NULL,
    kind VARCHAR(40) NOT NULL,
    text_value TEXT NOT NULL,
    redacted BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT runtime_transcript_part UNIQUE (attempt_id, part_id),
    CONSTRAINT runtime_transcript_sequence UNIQUE (job_id, sequence_number)
);

ALTER TABLE runtime_mock_response ADD COLUMN idempotency_key VARCHAR(160);
ALTER TABLE runtime_mock_response ADD COLUMN output_sequence_json TEXT;

CREATE INDEX runtime_input_attachment_job_idx ON runtime_input_attachment(job_id);
CREATE INDEX runtime_output_attempt_job_idx ON runtime_output_attempt(job_id, output_attempt_number);
CREATE INDEX runtime_transcript_job_idx ON runtime_transcript(job_id, id);
CREATE UNIQUE INDEX runtime_artifact_job_filename ON runtime_artifact(job_id, filename);
