CREATE TABLE runtime_v2_object (
    id VARCHAR(36) PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    state VARCHAR(30) NOT NULL,
    purpose VARCHAR(20) NOT NULL,
    filename VARCHAR(255) NOT NULL,
    mime_type VARCHAR(160) NOT NULL,
    size_bytes BIGINT NOT NULL,
    sha256 VARCHAR(64) NOT NULL,
    blob_key VARCHAR(500) NOT NULL UNIQUE,
    validation_error_code VARCHAR(120),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ready_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE runtime_v2_upload (
    id VARCHAR(36) PRIMARY KEY,
    object_id VARCHAR(36) NOT NULL REFERENCES runtime_v2_object(id),
    job_id VARCHAR(36),
    attempt_id VARCHAR(36),
    logical_name VARCHAR(100),
    direction VARCHAR(20) NOT NULL,
    state VARCHAR(30) NOT NULL,
    current_offset BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE runtime_v2_job (
    id VARCHAR(36) PRIMARY KEY,
    tenant_id VARCHAR(100) NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    job_kind VARCHAR(40) NOT NULL,
    task_type VARCHAR(60) NOT NULL,
    vendor_id VARCHAR(100) NOT NULL,
    model VARCHAR(160) NOT NULL,
    execution_mode VARCHAR(30) NOT NULL,
    request_json TEXT NOT NULL,
    status VARCHAR(40) NOT NULL,
    phase VARCHAR(80) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL,
    progress_percent INTEGER,
    progress_message VARCHAR(1000),
    result_json TEXT,
    error_code VARCHAR(120),
    error_message VARCHAR(2000),
    cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
    not_before TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    content_delete_requested_at TIMESTAMP WITH TIME ZONE,
    content_deleted_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT runtime_v2_job_idempotency UNIQUE (tenant_id, idempotency_key)
);

ALTER TABLE runtime_v2_upload ADD CONSTRAINT runtime_v2_upload_job_fk
    FOREIGN KEY (job_id) REFERENCES runtime_v2_job(id);

CREATE TABLE runtime_v2_job_object (
    job_id VARCHAR(36) NOT NULL REFERENCES runtime_v2_job(id),
    object_id VARCHAR(36) NOT NULL REFERENCES runtime_v2_object(id),
    direction VARCHAR(20) NOT NULL,
    role VARCHAR(40),
    logical_name VARCHAR(100) NOT NULL,
    sequence_number INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (job_id, object_id),
    CONSTRAINT runtime_v2_job_object_name UNIQUE (job_id, direction, logical_name)
);

CREATE TABLE runtime_v2_attempt (
    id VARCHAR(36) PRIMARY KEY,
    job_id VARCHAR(36) NOT NULL REFERENCES runtime_v2_job(id),
    worker_id VARCHAR(100) NOT NULL,
    worker_boot_id VARCHAR(100) NOT NULL,
    attempt_number INTEGER NOT NULL,
    reason VARCHAR(40) NOT NULL,
    status VARCHAR(40) NOT NULL,
    vendor_id VARCHAR(100) NOT NULL,
    model VARCHAR(160) NOT NULL,
    execution_mode VARCHAR(30) NOT NULL,
    task_type VARCHAR(60) NOT NULL,
    fencing_token_hash VARCHAR(64) NOT NULL,
    lease_until TIMESTAMP WITH TIME ZONE NOT NULL,
    attempt_deadline TIMESTAMP WITH TIME ZONE NOT NULL,
    heartbeat_at TIMESTAMP WITH TIME ZONE NOT NULL,
    provider_request_id VARCHAR(300),
    usage_quality VARCHAR(30) NOT NULL DEFAULT 'UNAVAILABLE',
    error_code VARCHAR(120),
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT runtime_v2_attempt_number UNIQUE (job_id, attempt_number)
);

ALTER TABLE runtime_v2_upload ADD CONSTRAINT runtime_v2_upload_attempt_fk
    FOREIGN KEY (attempt_id) REFERENCES runtime_v2_attempt(id);

CREATE TABLE runtime_v2_event (
    sequence_number BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id VARCHAR(36) NOT NULL REFERENCES runtime_v2_job(id),
    attempt_id VARCHAR(36),
    event_type VARCHAR(60) NOT NULL,
    phase VARCHAR(80),
    message VARCHAR(1000),
    log_kind VARCHAR(40),
    log_text VARCHAR(8192),
    log_stream_id VARCHAR(200),
    log_final BOOLEAN,
    job_status VARCHAR(40),
    progress_percent INTEGER,
    external_event_id VARCHAR(200),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT runtime_v2_event_idempotency UNIQUE (attempt_id, external_event_id)
);

CREATE TABLE runtime_v2_usage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id VARCHAR(36) NOT NULL REFERENCES runtime_v2_job(id),
    attempt_id VARCHAR(36) NOT NULL REFERENCES runtime_v2_attempt(id),
    external_event_id VARCHAR(200) NOT NULL,
    metric VARCHAR(60) NOT NULL,
    quantity DECIMAL(30, 9) NOT NULL,
    unit VARCHAR(30) NOT NULL,
    source VARCHAR(40) NOT NULL,
    observed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT runtime_v2_usage_idempotency UNIQUE (attempt_id, external_event_id, metric)
);

CREATE TABLE runtime_v2_cost (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id VARCHAR(36) NOT NULL REFERENCES runtime_v2_job(id),
    attempt_id VARCHAR(36),
    usage_id BIGINT REFERENCES runtime_v2_usage(id),
    price_rate_id VARCHAR(36),
    subscription_period_id VARCHAR(36),
    cost_kind VARCHAR(30) NOT NULL,
    cost_status VARCHAR(30) NOT NULL,
    amount DECIMAL(30, 9) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE runtime_v2_price_rate (
    id VARCHAR(36) PRIMARY KEY,
    version_number INTEGER NOT NULL,
    vendor_id VARCHAR(100) NOT NULL,
    model VARCHAR(160) NOT NULL,
    execution_mode VARCHAR(30) NOT NULL,
    task_type VARCHAR(60) NOT NULL,
    metric VARCHAR(60) NOT NULL,
    unit_size DECIMAL(30, 9) NOT NULL,
    unit_price DECIMAL(30, 9) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    valid_from TIMESTAMP WITH TIME ZONE NOT NULL,
    valid_until TIMESTAMP WITH TIME ZONE,
    source_reference VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT runtime_v2_price_version UNIQUE (vendor_id, model, execution_mode, task_type, metric, version_number)
);

ALTER TABLE runtime_v2_cost ADD CONSTRAINT runtime_v2_cost_price_fk
    FOREIGN KEY (price_rate_id) REFERENCES runtime_v2_price_rate(id);

CREATE TABLE runtime_v2_subscription_period (
    id VARCHAR(36) PRIMARY KEY,
    vendor_id VARCHAR(100) NOT NULL,
    model VARCHAR(160) NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    amount DECIMAL(30, 9) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    allocation_method VARCHAR(40) NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT runtime_v2_subscription_unique UNIQUE (vendor_id, model, period_start, period_end)
);

ALTER TABLE runtime_v2_cost ADD CONSTRAINT runtime_v2_cost_subscription_fk
    FOREIGN KEY (subscription_period_id) REFERENCES runtime_v2_subscription_period(id);

CREATE TABLE runtime_v2_worker (
    worker_id VARCHAR(100) PRIMARY KEY,
    boot_id VARCHAR(100) NOT NULL,
    executors_json TEXT NOT NULL,
    environment_keys_json TEXT NOT NULL,
    max_concurrency INTEGER NOT NULL,
    versions_json TEXT NOT NULL,
    last_heartbeat_at TIMESTAMP WITH TIME ZONE NOT NULL,
    registered_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX runtime_v2_object_tenant_idx ON runtime_v2_object(tenant_id, state, expires_at);
CREATE INDEX runtime_v2_upload_expiry_idx ON runtime_v2_upload(state, expires_at);
CREATE INDEX runtime_v2_job_queue_idx ON runtime_v2_job(status, not_before, created_at);
CREATE INDEX runtime_v2_job_tenant_idx ON runtime_v2_job(tenant_id, created_at);
CREATE INDEX runtime_v2_job_object_idx ON runtime_v2_job_object(job_id, direction, sequence_number);
CREATE INDEX runtime_v2_attempt_job_idx ON runtime_v2_attempt(job_id, attempt_number);
CREATE INDEX runtime_v2_attempt_lease_idx ON runtime_v2_attempt(status, lease_until);
CREATE INDEX runtime_v2_event_job_idx ON runtime_v2_event(job_id, sequence_number);
CREATE INDEX runtime_v2_usage_job_idx ON runtime_v2_usage(job_id, observed_at);
CREATE INDEX runtime_v2_cost_job_idx ON runtime_v2_cost(job_id, created_at);
CREATE INDEX runtime_v2_price_lookup_idx ON runtime_v2_price_rate(vendor_id, model, execution_mode, task_type, metric, valid_from);
